/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.0.10
 * Generated at: 2021-09-11 15:54:31 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.principal;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class navbarmainmenu_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("                      <nav class=\"pcoded-navbar\">\r\n");
      out.write("                      <div class=\"sidebar_toggle\"><a href=\"#\"><i class=\"icon-close icons\"></i></a></div>\r\n");
      out.write("                      <div class=\"pcoded-inner-navbar main-menu\">\r\n");
      out.write("                          <div class=\"\">\r\n");
      out.write("                              <div class=\"main-menu-header\">\r\n");
      out.write("                                  <img class=\"img-80 img-radius\" src=\"");
      out.print( request.getContextPath() );
      out.write("/assets/images/avatar-4.jpg\" alt=\"User-Profile-Image\">\r\n");
      out.write("                                  <div class=\"user-details\">\r\n");
      out.write("                                      <span id=\"more-details\">");
      out.print( session.getAttribute("usuario") );
      out.write("<i class=\"fa fa-caret-down\"></i></span>\r\n");
      out.write("                                  </div>\r\n");
      out.write("                              </div>\r\n");
      out.write("        \r\n");
      out.write("                              <div class=\"main-menu-content\">\r\n");
      out.write("                                  <ul>\r\n");
      out.write("                                      <li class=\"more-details\">\r\n");
      out.write("                                          <a href=\"user-profile.html\"><i class=\"ti-user\"></i>View Profile</a>\r\n");
      out.write("                                          <a href=\"#!\"><i class=\"ti-settings\"></i>Settings</a>\r\n");
      out.write("                                          <a href=\"");
      out.print( request.getContextPath() );
      out.write("/ServletLogin?acao=logout\"><i class=\"ti-layout-sidebar-left\"></i>Logout</a>\r\n");
      out.write("                                      </li>\r\n");
      out.write("                                  </ul>\r\n");
      out.write("                              </div>\r\n");
      out.write("                          </div>\r\n");
      out.write("                          <div class=\"p-15 p-b-0\">\r\n");
      out.write("                              <form class=\"form-material\">\r\n");
      out.write("                                  <div class=\"form-group form-primary\">\r\n");
      out.write("                                      <input type=\"text\" name=\"footer-email\" class=\"form-control\" required=\"\">\r\n");
      out.write("                                      <span class=\"form-bar\"></span>\r\n");
      out.write("                                      <label class=\"float-label\"><i class=\"fa fa-search m-r-10\"></i>Search Friend</label>\r\n");
      out.write("                                  </div>\r\n");
      out.write("                              </form>\r\n");
      out.write("                          </div>\r\n");
      out.write("                          <div class=\"pcoded-navigation-label\" data-i18n=\"nav.category.navigation\">Layout</div>\r\n");
      out.write("                          <ul class=\"pcoded-item pcoded-left-item\">\r\n");
      out.write("                              <li class=\"active\">\r\n");
      out.write("                                  <a href=\"index.html\" class=\"waves-effect waves-dark\">\r\n");
      out.write("                                      <span class=\"pcoded-micon\"><i class=\"ti-home\"></i><b>D</b></span>\r\n");
      out.write("                                      <span class=\"pcoded-mtext\" data-i18n=\"nav.dash.main\">Dashboard</span>\r\n");
      out.write("                                      <span class=\"pcoded-mcaret\"></span>\r\n");
      out.write("                                  </a>\r\n");
      out.write("                              </li>\r\n");
      out.write("                              <li class=\"pcoded-hasmenu\">\r\n");
      out.write("                                  <a href=\"javascript:void(0)\" class=\"waves-effect waves-dark\">\r\n");
      out.write("                                      <span class=\"pcoded-micon\"><i class=\"ti-layout-grid2-alt\"></i></span>\r\n");
      out.write("                                      <span class=\"pcoded-mtext\"  data-i18n=\"nav.basic-components.main\">Components</span>\r\n");
      out.write("                                      <span class=\"pcoded-mcaret\"></span>\r\n");
      out.write("                                  </a>\r\n");
      out.write("                                  <ul class=\"pcoded-submenu\">\r\n");
      out.write("                                      <li class=\" \">\r\n");
      out.write("                                          <a href=\"");
      out.print( request.getContextPath() );
      out.write("/principal/usuario.jsp\" class=\"waves-effect waves-dark\">\r\n");
      out.write("                                              <span class=\"pcoded-micon\"><i class=\"ti-angle-right\"></i></span>\r\n");
      out.write("                                              <span class=\"pcoded-mtext\" data-i18n=\"nav.basic-components.alert\">Usuario</span>\r\n");
      out.write("                                              <span class=\"pcoded-mcaret\"></span>\r\n");
      out.write("                                          </a>\r\n");
      out.write("                                      </li>\r\n");
      out.write("                                      <li class=\" \">\r\n");
      out.write("                                          <a href=\"breadcrumb.html\" class=\"waves-effect waves-dark\">\r\n");
      out.write("                                              <span class=\"pcoded-micon\"><i class=\"ti-angle-right\"></i></span>\r\n");
      out.write("                                              <span class=\"pcoded-mtext\" data-i18n=\"nav.basic-components.breadcrumbs\">Breadcrumbs</span>\r\n");
      out.write("                                              <span class=\"pcoded-mcaret\"></span>\r\n");
      out.write("                                          </a>\r\n");
      out.write("                                      </li>\r\n");
      out.write("                                      <li class=\" \">\r\n");
      out.write("                                          <a href=\"button.html\" class=\"waves-effect waves-dark\">\r\n");
      out.write("                                              <span class=\"pcoded-micon\"><i class=\"ti-angle-right\"></i></span>\r\n");
      out.write("                                              <span class=\"pcoded-mtext\" data-i18n=\"nav.basic-components.alert\">Button</span>\r\n");
      out.write("                                              <span class=\"pcoded-mcaret\"></span>\r\n");
      out.write("                                          </a>\r\n");
      out.write("                                      </li>\r\n");
      out.write("                                      <li class=\" \">\r\n");
      out.write("                                          <a href=\"tabs.html\" class=\"waves-effect waves-dark\">\r\n");
      out.write("                                              <span class=\"pcoded-micon\"><i class=\"ti-angle-right\"></i></span>\r\n");
      out.write("                                              <span class=\"pcoded-mtext\" data-i18n=\"nav.basic-components.breadcrumbs\">Tabs</span>\r\n");
      out.write("                                              <span class=\"pcoded-mcaret\"></span>\r\n");
      out.write("                                          </a>\r\n");
      out.write("                                      </li>\r\n");
      out.write("                                      <li class=\" \">\r\n");
      out.write("                                          <a href=\"color.html\" class=\"waves-effect waves-dark\">\r\n");
      out.write("                                              <span class=\"pcoded-micon\"><i class=\"ti-angle-right\"></i></span>\r\n");
      out.write("                                              <span class=\"pcoded-mtext\" data-i18n=\"nav.basic-components.alert\">Color</span>\r\n");
      out.write("                                              <span class=\"pcoded-mcaret\"></span>\r\n");
      out.write("                                          </a>\r\n");
      out.write("                                      </li>\r\n");
      out.write("                                      <li class=\" \">\r\n");
      out.write("                                          <a href=\"label-badge.html\" class=\"waves-effect waves-dark\">\r\n");
      out.write("                                              <span class=\"pcoded-micon\"><i class=\"ti-angle-right\"></i></span>\r\n");
      out.write("                                              <span class=\"pcoded-mtext\" data-i18n=\"nav.basic-components.breadcrumbs\">Label Badge</span>\r\n");
      out.write("                                              <span class=\"pcoded-mcaret\"></span>\r\n");
      out.write("                                          </a>\r\n");
      out.write("                                      </li>\r\n");
      out.write("                                      <li class=\" \">\r\n");
      out.write("                                          <a href=\"tooltip.html\" class=\"waves-effect waves-dark\">\r\n");
      out.write("                                              <span class=\"pcoded-micon\"><i class=\"ti-angle-right\"></i></span>\r\n");
      out.write("                                              <span class=\"pcoded-mtext\" data-i18n=\"nav.basic-components.alert\">Tooltip</span>\r\n");
      out.write("                                              <span class=\"pcoded-mcaret\"></span>\r\n");
      out.write("                                          </a>\r\n");
      out.write("                                      </li>\r\n");
      out.write("                                      <li class=\" \">\r\n");
      out.write("                                          <a href=\"typography.html\" class=\"waves-effect waves-dark\">\r\n");
      out.write("                                              <span class=\"pcoded-micon\"><i class=\"ti-angle-right\"></i></span>\r\n");
      out.write("                                              <span class=\"pcoded-mtext\" data-i18n=\"nav.basic-components.breadcrumbs\">Typography</span>\r\n");
      out.write("                                              <span class=\"pcoded-mcaret\"></span>\r\n");
      out.write("                                          </a>\r\n");
      out.write("                                      </li>\r\n");
      out.write("                                      <li class=\" \">\r\n");
      out.write("                                          <a href=\"notification.html\" class=\"waves-effect waves-dark\">\r\n");
      out.write("                                              <span class=\"pcoded-micon\"><i class=\"ti-angle-right\"></i></span>\r\n");
      out.write("                                              <span class=\"pcoded-mtext\" data-i18n=\"nav.basic-components.alert\">Notification</span>\r\n");
      out.write("                                              <span class=\"pcoded-mcaret\"></span>\r\n");
      out.write("                                          </a>\r\n");
      out.write("                                      </li>\r\n");
      out.write("                                      <li class=\" \">\r\n");
      out.write("                                          <a href=\"icon-themify.html\" class=\"waves-effect waves-dark\">\r\n");
      out.write("                                              <span class=\"pcoded-micon\"><i class=\"ti-angle-right\"></i></span>\r\n");
      out.write("                                              <span class=\"pcoded-mtext\" data-i18n=\"nav.basic-components.breadcrumbs\">Themify</span>\r\n");
      out.write("                                              <span class=\"pcoded-mcaret\"></span>\r\n");
      out.write("                                          </a>\r\n");
      out.write("                                      </li>\r\n");
      out.write("                \r\n");
      out.write("                                  </ul>\r\n");
      out.write("                              </li>\r\n");
      out.write("                          </ul>\r\n");
      out.write("                          <div class=\"pcoded-navigation-label\" data-i18n=\"nav.category.forms\">Forms &amp; Tables</div>\r\n");
      out.write("                          <ul class=\"pcoded-item pcoded-left-item\">\r\n");
      out.write("                              <li>\r\n");
      out.write("                                  <a href=\"form-elements-component.html\" class=\"waves-effect waves-dark\">\r\n");
      out.write("                                      <span class=\"pcoded-micon\"><i class=\"ti-layers\"></i><b>FC</b></span>\r\n");
      out.write("                                      <span class=\"pcoded-mtext\" data-i18n=\"nav.form-components.main\">Form Components</span>\r\n");
      out.write("                                      <span class=\"pcoded-mcaret\"></span>\r\n");
      out.write("                                  </a>\r\n");
      out.write("                              </li>\r\n");
      out.write("                              <li>\r\n");
      out.write("                                  <a href=\"bs-basic-table.html\" class=\"waves-effect waves-dark\">\r\n");
      out.write("                                      <span class=\"pcoded-micon\"><i class=\"ti-layers\"></i><b>FC</b></span>\r\n");
      out.write("                                      <span class=\"pcoded-mtext\" data-i18n=\"nav.form-components.main\">Basic Table</span>\r\n");
      out.write("                                      <span class=\"pcoded-mcaret\"></span>\r\n");
      out.write("                                  </a>\r\n");
      out.write("                              </li>\r\n");
      out.write("        \r\n");
      out.write("                          </ul>\r\n");
      out.write("        \r\n");
      out.write("                          <div class=\"pcoded-navigation-label\" data-i18n=\"nav.category.forms\">Chart &amp; Maps</div>\r\n");
      out.write("                          <ul class=\"pcoded-item pcoded-left-item\">\r\n");
      out.write("                              <li>\r\n");
      out.write("                                  <a href=\"chart.html\" class=\"waves-effect waves-dark\">\r\n");
      out.write("                                      <span class=\"pcoded-micon\"><i class=\"ti-layers\"></i><b>FC</b></span>\r\n");
      out.write("                                      <span class=\"pcoded-mtext\" data-i18n=\"nav.form-components.main\">Chart</span>\r\n");
      out.write("                                      <span class=\"pcoded-mcaret\"></span>\r\n");
      out.write("                                  </a>\r\n");
      out.write("                              </li>\r\n");
      out.write("                              <li>\r\n");
      out.write("                                  <a href=\"map-google.html\" class=\"waves-effect waves-dark\">\r\n");
      out.write("                                      <span class=\"pcoded-micon\"><i class=\"ti-layers\"></i><b>FC</b></span>\r\n");
      out.write("                                      <span class=\"pcoded-mtext\" data-i18n=\"nav.form-components.main\">Maps</span>\r\n");
      out.write("                                      <span class=\"pcoded-mcaret\"></span>\r\n");
      out.write("                                  </a>\r\n");
      out.write("                              </li>\r\n");
      out.write("                              <li class=\"pcoded-hasmenu\">\r\n");
      out.write("                                  <a href=\"javascript:void(0)\" class=\"waves-effect waves-dark\">\r\n");
      out.write("                                      <span class=\"pcoded-micon\"><i class=\"ti-layout-grid2-alt\"></i></span>\r\n");
      out.write("                                      <span class=\"pcoded-mtext\"  data-i18n=\"nav.basic-components.main\">Pages</span>\r\n");
      out.write("                                      <span class=\"pcoded-mcaret\"></span>\r\n");
      out.write("                                  </a>\r\n");
      out.write("                                  <ul class=\"pcoded-submenu\">\r\n");
      out.write("                                      <li class=\" \">\r\n");
      out.write("                                          <a href=\"auth-normal-sign-in.html\" class=\"waves-effect waves-dark\">\r\n");
      out.write("                                              <span class=\"pcoded-micon\"><i class=\"ti-angle-right\"></i></span>\r\n");
      out.write("                                              <span class=\"pcoded-mtext\" data-i18n=\"nav.basic-components.alert\">Login</span>\r\n");
      out.write("                                              <span class=\"pcoded-mcaret\"></span>\r\n");
      out.write("                                          </a>\r\n");
      out.write("                                      </li>\r\n");
      out.write("                                      <li class=\" \">\r\n");
      out.write("                                          <a href=\"auth-sign-up.html\" class=\"waves-effect waves-dark\">\r\n");
      out.write("                                              <span class=\"pcoded-micon\"><i class=\"ti-angle-right\"></i></span>\r\n");
      out.write("                                              <span class=\"pcoded-mtext\" data-i18n=\"nav.basic-components.breadcrumbs\">Register</span>\r\n");
      out.write("                                              <span class=\"pcoded-mcaret\"></span>\r\n");
      out.write("                                          </a>\r\n");
      out.write("                                      </li>\r\n");
      out.write("                                      <li class=\" \">\r\n");
      out.write("                                          <a href=\"sample-page.html\" class=\"waves-effect waves-dark\">\r\n");
      out.write("                                              <span class=\"pcoded-micon\"><i class=\"ti-angle-right\"></i></span>\r\n");
      out.write("                                              <span class=\"pcoded-mtext\" data-i18n=\"nav.basic-components.breadcrumbs\">Sample Page</span>\r\n");
      out.write("                                              <span class=\"pcoded-mcaret\"></span>\r\n");
      out.write("                                          </a>\r\n");
      out.write("                                      </li>\r\n");
      out.write("                                  </ul>\r\n");
      out.write("                              </li>\r\n");
      out.write("        \r\n");
      out.write("                          </ul>\r\n");
      out.write("        \r\n");
      out.write("                          <div class=\"pcoded-navigation-label\" data-i18n=\"nav.category.other\">Other</div>\r\n");
      out.write("                          <ul class=\"pcoded-item pcoded-left-item\">\r\n");
      out.write("                              <li class=\"pcoded-hasmenu \">\r\n");
      out.write("                                  <a href=\"javascript:void(0)\" class=\"waves-effect waves-dark\">\r\n");
      out.write("                                      <span class=\"pcoded-micon\"><i class=\"ti-direction-alt\"></i><b>M</b></span>\r\n");
      out.write("                                      <span class=\"pcoded-mtext\" data-i18n=\"nav.menu-levels.main\">Menu Levels</span>\r\n");
      out.write("                                      <span class=\"pcoded-mcaret\"></span>\r\n");
      out.write("                                  </a>\r\n");
      out.write("                                  <ul class=\"pcoded-submenu\">\r\n");
      out.write("                                      <li class=\"\">\r\n");
      out.write("                                          <a href=\"javascript:void(0)\" class=\"waves-effect waves-dark\">\r\n");
      out.write("                                              <span class=\"pcoded-micon\"><i class=\"ti-angle-right\"></i></span>\r\n");
      out.write("                                              <span class=\"pcoded-mtext\" data-i18n=\"nav.menu-levels.menu-level-21\">Menu Level 2.1</span>\r\n");
      out.write("                                              <span class=\"pcoded-mcaret\"></span>\r\n");
      out.write("                                          </a>\r\n");
      out.write("                                      </li>\r\n");
      out.write("                                      <li class=\"pcoded-hasmenu \">\r\n");
      out.write("                                          <a href=\"javascript:void(0)\" class=\"waves-effect waves-dark\">\r\n");
      out.write("                                              <span class=\"pcoded-micon\"><i class=\"ti-direction-alt\"></i></span>\r\n");
      out.write("                                              <span class=\"pcoded-mtext\" data-i18n=\"nav.menu-levels.menu-level-22.main\">Menu Level 2.2</span>\r\n");
      out.write("                                              <span class=\"pcoded-mcaret\"></span>\r\n");
      out.write("                                          </a>\r\n");
      out.write("                                          <ul class=\"pcoded-submenu\">\r\n");
      out.write("                                              <li class=\"\">\r\n");
      out.write("                                                  <a href=\"javascript:void(0)\" class=\"waves-effect waves-dark\">\r\n");
      out.write("                                                      <span class=\"pcoded-micon\"><i class=\"ti-angle-right\"></i></span>\r\n");
      out.write("                                                      <span class=\"pcoded-mtext\" data-i18n=\"nav.menu-levels.menu-level-22.menu-level-31\">Menu Level 3.1</span>\r\n");
      out.write("                                                      <span class=\"pcoded-mcaret\"></span>\r\n");
      out.write("                                                  </a>\r\n");
      out.write("                                              </li>\r\n");
      out.write("                                          </ul>\r\n");
      out.write("                                      </li>\r\n");
      out.write("                                      <li class=\"\">\r\n");
      out.write("                                          <a href=\"javascript:void(0)\" class=\"waves-effect waves-dark\">\r\n");
      out.write("                                              <span class=\"pcoded-micon\"><i class=\"ti-angle-right\"></i></span>\r\n");
      out.write("                                              <span class=\"pcoded-mtext\" data-i18n=\"nav.menu-levels.menu-level-23\">Menu Level 2.3</span>\r\n");
      out.write("                                              <span class=\"pcoded-mcaret\"></span>\r\n");
      out.write("                                          </a>\r\n");
      out.write("                                      </li>\r\n");
      out.write("                \r\n");
      out.write("                                  </ul>\r\n");
      out.write("                              </li>\r\n");
      out.write("                          </ul>\r\n");
      out.write("                      </div>\r\n");
      out.write("                  </nav>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
